name: CI

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    branches:
      - main

jobs:
  build-test-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: recursive

      - name: configure libaes_siv
        run: cd libaes_siv && cmake .

      - name: build libaes_siv
        run: make -C libaes_siv

      - name: install gcrypt
        run: sudo apt-get install libgcrypt20-dev

      - name: build with gcc
        run: CC="gcc -Werror" make -B -C src CRYPTO=openssl all

      - name: build with clang
        run: CC="clang -fsanitize=address,integer,undefined -Werror" make -B -C src CRYPTO=openssl all

      - name: test with gcrypt
        run: CC="clang -fsanitize=address,integer,undefined -Werror" make -C src CRYPTO=gcrypt test

      - name: test with libaes_siv
        run: CC="clang -fsanitize=address,integer,undefined -Werror" make -C src CRYPTO=libaes_siv test

      - name: test with openssl
        run: |
          CC="clang -fsanitize=address,integer,undefined -Werror -DOPENSSL_WORKAROUND" make -C src -B nts_extfields.o
          CC="clang -fsanitize=address,integer,undefined -Werror" make -C src CRYPTO=openssl test

      - name: install clang-tools
        run: |
          sudo apt-get update
          sudo apt-get install --yes clang-tools

      - name: run analysis
        run: scan-build --status-bugs make -B -C src all

  smoke-test-ntp:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: recursive

      - name: install AFL
        run: |
          sudo apt-get update
          sudo apt-get install --yes afl++

      - name: build fuzz test
        run: CC="afl-clang -fsanitize=address,integer,undefined -Wno-strict-prototypes -Werror" make -C src nts_fuzz

      - name: fuzz test NTS responses
        run: |
          echo core | sudo tee /proc/sys/kernel/core_pattern
          AFL_BENCH_UNTIL_CRASH=1 CC="afl-clang -fsanitize=address,integer,undefined" FUZZTIME=90 make -C src fuzz_ntp

  smoke-test-ntske:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: recursive

      - name: install AFL
        run: |
          sudo apt-get update
          sudo apt-get install --yes afl++

      - name: build fuzz test
        run: CC="afl-clang -fsanitize=address,integer,undefined -Wno-strict-prototypes -Werror" make -C src nts_fuzz

      - name: fuzz test NTS responses
        run: |
          echo core | sudo tee /proc/sys/kernel/core_pattern
          AFL_BENCH_UNTIL_CRASH=1 CC="afl-clang -fsanitize=address,integer,undefined" FUZZTIME=90 make -C src fuzz_ntske
