name: CI

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    branches:
      - main

jobs:
  check-portability:
    runs-on: ubuntu-latest
    container: debian:trixie
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: install sudo for syntax reasons
        run: |
          apt-get update
          apt-get install -y sudo

      - name: install dependencies for all architectures supported by trixie
        run: |
          #for arch in i386 s390x arm64 riscv64 armel armhf ppc64el; do 
          #   sudo dpkg --add-architecture $arch
          # done
           sudo apt-get update
           sudo apt-get install -y ca-certificates
           sudo apt-get install -y make gcc # libc6-dev-i386
           #for foreign in s390x aarch64 riscv64 powerpc64le; do
           #  sudo apt-get install -y gcc-$foreign-linux-gnu
           #done
           #sudo apt-get install -y gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf
           for arch in amd64; do # i386 s390x arm64 riscv64 armel armhf ppc64el; do
             sudo apt-get install -y libssl-dev:$arch libgnutls28-dev:$arch libgcrypt20-dev:$arch
           done

      - name: full test on all platform-TLS-crypto combinations
        run: |
          export CC
          for CC in "gcc -m64"; do
            #"gcc -m32"
            #s390x-linux-gnu-gcc
            #aarch64-linux-gnu-gcc
            #riscv64-linux-gnu-gcc
            #arm-linux-gnueabi-gcc
            #arm-linux-gnueabihf-gcc
            #powerpc64le-linux-gnu-gcc
            make -C src clean
            for tls in openssl gnutls; do
            for crypto in openssl nettle; do
              echo "[$CC] $tls+$crypto"
              make TLS=$tls CRYPTO=$crypto -C src test demo && src/demo time.cloudflare.com | grep -q 'offset'
            done
            done
          done
