name: CI

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    branches:
      - main

jobs:
  check-portability:
    runs-on: ubuntu-latest
    container: debian:trixie
    steps:
      - name: install dependencies for all architectures supported by trixie
        run: |
           for arch in i386 s390x arm64 riscv64 armel armhf ppc64el; do 
              dpkg --add-architecture $arch
           done
           apt-get update
           (
             echo binfmt-support qemu-user-static
             echo ca-certificates make gcc
             for foreign in i686 s390x aarch64 riscv64 powerpc64le; do
               echo gcc-$foreign-linux-gnu
             done
             echo gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf
             for arch in amd64 i386 s390x arm64 riscv64 armel armhf ppc64el; do
               echo libssl-dev:$arch libgnutls28-dev:$arch libgcrypt20-dev:$arch
             done
           ) | xargs apt-get install -y

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: full test on all platform-TLS-crypto combinations
        run: |
          export CFLAGS='-Wall -Wextra -pedantic -std=gnu11'
          export CC
          for CC in \
            gcc i686-linux-gnu-gcc s390x-linux-gnu-gcc aarch64-linux-gnu-gcc riscv64-linux-gnu-gcc \
            arm-linux-gnueabi-gcc arm-linux-gnueabihf-gcc powerpc64le-linux-gnu-gcc
          do
            make -C src clean
            for tls in openssl gnutls; do
            for crypto in openssl nettle; do
              echo "[$CC] $tls+$crypto"
              make TLS=$tls CRYPTO=$crypto -C src -B test demo && src/demo time.cloudflare.com | grep -q 'offset'
            done
            done
          done
